package com.ringdroid.data.model

// Custom exception for invalid inputs.
class InvalidInputException(message: String?) : Exception(message) {
    companion object {
        // Serial version ID generated by Eclipse.
        private const val serialVersionUID = -2505698991597837165L
    }
}// just a fixed value here...